#!/bin/sh
set -e
echo "Syncing DB"
exec /sbin/setuser pymc /usr/bin/python /var/lib/pymc/manageMC/manage.py syncdb
echo "Starting uwsgi"
exec /sbin/setuser pymc /usr/bin/uwsgi /var/lib/pymc/uwsgi.ini \
        >> /var/lib/pymc/pymc.io.log 2>&1
